version: '2'
services:
  api:
    build: api/
    ports:
     - "8082:8000"
  ui:
    build: ui/
    ports:
     - "8080:80"
  swagger-ui:
    image: schickling/swagger-ui
    ports:
      - 8081:80
    links:
      - api
    environment:
      - API_URL=http://127.0.0.1:8082/api
